# Generated by Django 5.2.7 on 2025-10-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0002_movie_description_en_movie_description_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moments',
            name='movie_moments_en',
            field=models.ImageField(null=True, upload_to='movie_moments/'),
        ),
        migrations.AddField(
            model_name='moments',
            name='movie_moments_ky',
            field=models.ImageField(null=True, upload_to='movie_moments/'),
        ),
        migrations.AddField(
            model_name='moments',
            name='movie_moments_ru',
            field=models.ImageField(null=True, upload_to='movie_moments/'),
        ),
    ]
