# Generated by Django 5.2.7 on 2025-10-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0003_moments_movie_moments_en_moments_movie_moments_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
