# Generated by Django 5.2.7 on 2025-10-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0004_alter_director_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ky',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_ky',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='director_name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='movie_languages_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='movie_languages_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='movielanguages',
            name='movie_languages_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
