# Generated by Django 5.2.7 on 2025-10-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0005_actor_actor_name_en_actor_actor_name_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='Gere_name_en',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='Gere_name_ky',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='genre',
            name='Gere_name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
