# Generated by Django 5.2.7 on 2025-10-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0006_genre_gere_name_en_genre_gere_name_ky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(),
        ),
    ]
