# Generated by Django 5.2.7 on 2025-10-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0007_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(),
        ),
    ]
