# Generated by Django 5.2.7 on 2025-10-18 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0008_alter_movie_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielanguages',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='moview.movie'),
        ),
    ]
