# Generated by Django 5.2.7 on 2025-10-21 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0009_alter_movielanguages_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moments',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='moview.movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status_movie',
            field=models.CharField(choices=[('Diamond', 'Diamond'), ('simple', 'simple')], default='simple', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('Diamond', 'Diamond'), ('simple', 'simple')], default='simple', max_length=32),
        ),
    ]
