# Generated by Django 5.2.7 on 2025-10-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0010_alter_moments_movie_alter_movie_status_movie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='data_type',
            field=models.CharField(choices=[('144', '144'), ('360', '360'), ('480', '480'), ('720', '720'), ('1080', '1080'), ('1440', '1440'), ('2160', '2160')], max_length=10),
        ),
    ]
