# Generated by Django 5.2.7 on 2025-10-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0012_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actor_movie', to='moview.actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(related_name='director_movie', to='moview.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='genre_movie', to='moview.genre'),
        ),
    ]
