# Generated by Django 5.2.7 on 2025-10-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moview', '0013_alter_movie_actor_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='country_movie', to='moview.country'),
        ),
    ]
